# Generated by Django 2.0.2 on 2018-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7, verbose_name='Nome')),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('entrada', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('saida_almoco', models.DateTimeField(verbose_name='Saida do Almoço')),
                ('volta_almoco', models.DateTimeField(verbose_name='Volta do Almoço')),
                ('saida', models.DateTimeField(verbose_name='Horário de saida')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
