# Generated by Django 2.0.2 on 2018-02-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4, verbose_name='Nº')),
                ('mod', models.CharField(max_length=7, verbose_name='Mod')),
                ('motorista', models.CharField(max_length=50, verbose_name='Motorista')),
                ('placa', models.CharField(max_length=7, verbose_name='placa')),
                ('entrada', models.DateTimeField(verbose_name='Hora de entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de saida')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
            },
        ),
    ]
