# Generated by Django 2.0.2 on 2018-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('autorizado', models.CharField(max_length=100, verbose_name='Autorizado por')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('placa', models.CharField(max_length=100, verbose_name='Placa')),
                ('entrada', models.DateTimeField(verbose_name='Hora de entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de saida')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
    ]
