# Generated by Django 2.0.2 on 2018-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='setor',
            field=models.CharField(max_length=100, verbose_name='Setor Visitado'),
        ),
    ]
