# Generated by Django 2.0.2 on 2018-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('motorista', models.CharField(max_length=50, verbose_name='Motorista')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('nota', models.CharField(max_length=15, verbose_name='Nota Fiscal')),
                ('entrega', models.DateTimeField(verbose_name='Hora da entrega')),
                ('entrada', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de saida')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
